# -*- coding: utf-8 -*-
"""initial_schema

Начальная схема базы данных.

Таблицы:
- users: пользователи бота
- messages: история сообщений (для контекста AI)
- generations: статистика генераций (для cooldown и аналитики)
- transactions: леджер баланса токенов
- payments: история платежей
- subscriptions: подписки на тарифы
- referrals: реферальная программа
- broadcasts: массовые рассылки

Revision ID: 965df8d6b696
Revises:
Create Date: 2026-01-08 12:57:36.012780

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "965df8d6b696"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=True),
        sa.Column("first_name", sa.String(length=255), nullable=True),
        sa.Column("last_name", sa.String(length=255), nullable=True),
        sa.Column("language", sa.String(length=10), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("source", sa.String(length=255), nullable=True),
        sa.Column("balance", sa.Integer(), nullable=False),
        sa.Column("is_blocked", sa.Boolean(), nullable=False),
        sa.Column("terms_accepted_at", sa.DateTime(), nullable=True),
        sa.Column("accepted_legal_version", sa.String(length=50), nullable=True),
        sa.Column("registration_bonus_granted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_telegram_id"), "users", ["telegram_id"], unique=True)
    op.create_table(
        "broadcasts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("message_text", sa.Text(), nullable=False),
        sa.Column("parse_mode", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_by_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("filter_language", sa.String(length=10), nullable=True),
        sa.Column("filter_has_payments", sa.Boolean(), nullable=True),
        sa.Column("filter_source", sa.String(length=255), nullable=True),
        sa.Column("filter_registered_after", sa.DateTime(), nullable=True),
        sa.Column("filter_registered_before", sa.DateTime(), nullable=True),
        sa.Column("filter_exclude_blocked", sa.Boolean(), nullable=False),
        sa.Column("total_recipients", sa.Integer(), nullable=False),
        sa.Column("sent_count", sa.Integer(), nullable=False),
        sa.Column("failed_count", sa.Integer(), nullable=False),
        sa.Column("last_processed_user_id", sa.BigInteger(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_broadcasts_status"), "broadcasts", ["status"], unique=False
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("model_key", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_messages_created_at"), "messages", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_messages_model_key"), "messages", ["model_key"], unique=False
    )
    op.create_index(op.f("ix_messages_user_id"), "messages", ["user_id"], unique=False)
    op.create_table(
        "payments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("provider_payment_id", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=10), nullable=False),
        sa.Column("tariff_slug", sa.String(length=100), nullable=False),
        sa.Column("tokens_amount", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("payment_method_id", sa.String(length=255), nullable=True),
        sa.Column("metadata_json", sa.Text(), nullable=True),
        sa.Column("is_recurring", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_payments_provider_payment_id",
        "payments",
        ["provider", "provider_payment_id"],
        unique=True,
    )
    op.create_index(
        "ix_payments_status_created", "payments", ["status", "created_at"], unique=False
    )
    op.create_index(
        "ix_payments_user_created", "payments", ["user_id", "created_at"], unique=False
    )
    op.create_table(
        "referrals",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("inviter_id", sa.BigInteger(), nullable=False),
        sa.Column("invitee_id", sa.BigInteger(), nullable=False),
        sa.Column("inviter_bonus_amount", sa.Integer(), nullable=False),
        sa.Column("invitee_bonus_amount", sa.Integer(), nullable=False),
        sa.Column("bonus_paid_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["invitee_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["inviter_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("invitee_id"),
    )
    op.create_index(
        "ix_referrals_inviter_bonus",
        "referrals",
        ["inviter_id", "bonus_paid_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_referrals_inviter_id"), "referrals", ["inviter_id"], unique=False
    )
    op.create_index(
        "ix_referrals_unpaid_bonuses",
        "referrals",
        ["inviter_id"],
        unique=False,
        postgresql_where=sa.text("bonus_paid_at IS NULL"),
    )
    op.create_table(
        "transactions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("balance_after", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("metadata_json", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_transactions_user_created",
        "transactions",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_transactions_user_type", "transactions", ["user_id", "type"], unique=False
    )
    op.create_table(
        "generations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("generation_type", sa.String(length=50), nullable=False),
        sa.Column("model_key", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("tokens_charged", sa.Integer(), nullable=False),
        sa.Column("cost_rub", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("transaction_id", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["transaction_id"], ["transactions.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_generations_created_at"), "generations", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_generations_generation_type"),
        "generations",
        ["generation_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_generations_transaction_id"),
        "generations",
        ["transaction_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_generations_user_id"), "generations", ["user_id"], unique=False
    )
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("tariff_slug", sa.String(length=100), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "ACTIVE",
                "PAST_DUE",
                "CANCELED",
                "EXPIRED",
                name="subscriptionstatus",
                native_enum=False,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column("tokens_per_period", sa.Integer(), nullable=False),
        sa.Column("tokens_remaining", sa.Integer(), nullable=False),
        sa.Column("period_start", sa.DateTime(), nullable=False),
        sa.Column("period_end", sa.DateTime(), nullable=False),
        sa.Column("auto_renewal", sa.Boolean(), nullable=False),
        sa.Column("cancel_at_period_end", sa.Boolean(), nullable=False),
        sa.Column("payment_method_id", sa.String(length=255), nullable=True),
        sa.Column("original_payment_id", sa.Integer(), nullable=True),
        sa.Column("last_renewal_payment_id", sa.Integer(), nullable=True),
        sa.Column("renewal_attempts", sa.Integer(), nullable=False),
        sa.Column("last_renewal_attempt_at", sa.DateTime(), nullable=True),
        sa.Column("metadata_json", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["last_renewal_payment_id"], ["payments.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["original_payment_id"], ["payments.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_subscriptions_status_period_end",
        "subscriptions",
        ["status", "period_end"],
        unique=False,
    )
    op.create_index(
        "ix_subscriptions_tariff", "subscriptions", ["tariff_slug"], unique=False
    )
    op.create_index(
        "ix_subscriptions_user_status",
        "subscriptions",
        ["user_id", "status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_subscriptions_user_status", table_name="subscriptions")
    op.drop_index("ix_subscriptions_tariff", table_name="subscriptions")
    op.drop_index("ix_subscriptions_status_period_end", table_name="subscriptions")
    op.drop_table("subscriptions")
    op.drop_index(op.f("ix_generations_user_id"), table_name="generations")
    op.drop_index(op.f("ix_generations_transaction_id"), table_name="generations")
    op.drop_index(op.f("ix_generations_generation_type"), table_name="generations")
    op.drop_index(op.f("ix_generations_created_at"), table_name="generations")
    op.drop_table("generations")
    op.drop_index("ix_transactions_user_type", table_name="transactions")
    op.drop_index("ix_transactions_user_created", table_name="transactions")
    op.drop_table("transactions")
    op.drop_index(
        "ix_referrals_unpaid_bonuses",
        table_name="referrals",
        postgresql_where=sa.text("bonus_paid_at IS NULL"),
    )
    op.drop_index(op.f("ix_referrals_inviter_id"), table_name="referrals")
    op.drop_index("ix_referrals_inviter_bonus", table_name="referrals")
    op.drop_table("referrals")
    op.drop_index("ix_payments_user_created", table_name="payments")
    op.drop_index("ix_payments_status_created", table_name="payments")
    op.drop_index("ix_payments_provider_payment_id", table_name="payments")
    op.drop_table("payments")
    op.drop_index(op.f("ix_messages_user_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_model_key"), table_name="messages")
    op.drop_index(op.f("ix_messages_created_at"), table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_broadcasts_status"), table_name="broadcasts")
    op.drop_table("broadcasts")
    op.drop_index(op.f("ix_users_telegram_id"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
